[project]
name = "Call-Me-Maybe"
version = "0.1.0"
description = "tlaranje's call_me_maybe project (school 42)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fire>=0.7.1",
    "flake8>=7.3.0",
    "mypy>=1.19.1",
    "numpy>=2.4.1",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "torch>=2.10.0",
    "transformers>=5.0.0",
    "accelerate>=1.10.0",
    "rich>=13.7.0"
]

[tool.mypy]
files = ["src", "tests"]
exclude = "build|dist|.venv|site-packages"
ignore_missing_imports = true
cache_dir = ".mypy_cache"

[[tool.mypy.overrides]]
module = [
    "torch.*",
    "transformers.*",
    "accelerate.*",
    "huggingface_hub.*",
    "tokenizers.*",
    "safetensors.*",
]
ignore_errors = true
ignore_missing_imports = true
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "src.llm_utils"
ignore_errors = true

[[tool.mypy.overrides]]
module = "uvcache.*"
ignore_errors = true
